version: '3.8'

services:
  # MariaDB Database Container
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Testingtesting1234
      MYSQL_DATABASE: KartverketDb1
      MYSQL_USER: root
      MYSQL_PASSWORD: Testingtesting1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  # Application Container (Kartverket)
  kartverket:
    image: ${DOCKER_REGISTRY:-kartverket} # Defaulting DOCKER_REGISTRY if not set
    build:
      context: .
      dockerfile: Kartverket/Dockerfile
    container_name: kartverket
    environment:
      ASPNETCORE_URLS: "http://+/"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mariadb;Port=3306;Database=KartverketDb;User=root;Password=Testingtesting1234;"
    ports:
      - "5266:80"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data:
