version: '3.8'

services:
  # MariaDB Database Container
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Testingtesting1234
      MYSQL_DATABASE: KartverketDb
      MYSQL_USER: root
      MYSQL_PASSWORD: Testingtesting1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  # Application Container (Kartverket)
  kartverket:
    image: ${DOCKER_REGISTRY-}kartverket
    build: 
      context: .
      dockerfile: Kartverket/Dockerfile
    container_name: kartverket
    environment:
      ConnectionString__DefaultConnection: "Server=localhost;Database=KartverketDb;User=root;Password=Testingtesting1234;"
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data:
